name: Release Latest
run-name: Release latest
on:
  push:
    tags:
      - 'master'
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: ./build.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: profilerate.latest.tar.gz
        asset_name: profilerate.latest.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        body: "Latest Release"
